### ISSUE TITLE
vfs_rar license issue

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [shaohao/vfs_rar#2]
Hello

Your plugin code seems to be licensed under GPLv2, while unrar source is using Unrar freeware license, which is incompatible with GPL.

This makes distributing this plugin in binary form illegal, and I'm considering pulling it from deadbeef.sf.net plugins page.

Can you please relicense your code under some license compatible with unrar sources?

I suggest using BSD or MIT license.

Best regards.

**Comment by shaohao** [comment]
Migrated to MTI instead.

**Comment by shaohao** [comment]
Migrate to MTI instead.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Alexey-Yakovenko** [comment]
Thanks!
